
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**

 @author mattk
 */
public class addPersonFrame extends javax.swing.JInternalFrame
{
   private Department dept;
   private Bag persBag = new Bag();
   private Bag corsBag = new Bag();
   private String role;
   /**
    Creates new form addPersonFrame
    */
   public addPersonFrame(Department department)
   {
      this.dept = department;
      initComponents();
      setTitle("Add Person");
      setSize(275, 140);
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txt_addPersonName = new javax.swing.JTextField();
        txt_addPersonId = new javax.swing.JTextField();
        lbl_addPersonName = new javax.swing.JLabel();
        lbl_addPersonId = new javax.swing.JLabel();
        btn_addPersonAdd = new javax.swing.JButton();
        radBtn_Stud = new javax.swing.JRadioButton();
        radBtn_Prof = new javax.swing.JRadioButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setClosable(true);

        lbl_addPersonName.setText("Name");

        lbl_addPersonId.setText("Id");

        btn_addPersonAdd.setText("Add");
        btn_addPersonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addPersonAddActionPerformed(evt);
            }
        });

        buttonGroup1.add(radBtn_Stud);
        radBtn_Stud.setText("Student");
        radBtn_Stud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtn_StudActionPerformed(evt);
            }
        });

        buttonGroup1.add(radBtn_Prof);
        radBtn_Prof.setText("Professor");
        radBtn_Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtn_ProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_addPersonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_addPersonName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_addPersonId, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_addPersonName)
                            .addComponent(txt_addPersonId, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBtn_Stud)
                    .addComponent(radBtn_Prof))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_addPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addPersonName)
                    .addComponent(radBtn_Stud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_addPersonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addPersonId)
                    .addComponent(radBtn_Prof))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addPersonAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void btn_addPersonAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_addPersonAddActionPerformed
   {//GEN-HEADEREND:event_btn_addPersonAddActionPerformed
        // TODO add your handling code here:
        String name = txt_addPersonName.getText();
        String id = txt_addPersonId.getText();
        try
        {
            dept.isIdValid(id);
        }
      
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        if (role == null)
            JOptionPane.showMessageDialog(addPersonFrame.this, "Please select a role");
        else
            dept.addPerson(id, name, role);
            txt_addPersonName.setText("");
            txt_addPersonId.setText("");
            if (radBtn_Stud.isSelected())
                radBtn_Stud.setSelected(false);
            if (radBtn_Prof.isSelected())
                radBtn_Prof.setSelected(false);
   }//GEN-LAST:event_btn_addPersonAddActionPerformed

   private void radBtn_StudActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radBtn_StudActionPerformed
   {//GEN-HEADEREND:event_radBtn_StudActionPerformed
      // TODO add your handling code here:
      if (radBtn_Stud.isSelected())
         role = "Student";
      else
         role = null;
   }//GEN-LAST:event_radBtn_StudActionPerformed

   private void radBtn_ProfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radBtn_ProfActionPerformed
   {//GEN-HEADEREND:event_radBtn_ProfActionPerformed
      // TODO add your handling code here:
      if (radBtn_Prof.isSelected())
         role = "Professor";
      else
         role = null;
   }//GEN-LAST:event_radBtn_ProfActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addPersonAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lbl_addPersonId;
    private javax.swing.JLabel lbl_addPersonName;
    private javax.swing.JRadioButton radBtn_Prof;
    private javax.swing.JRadioButton radBtn_Stud;
    private javax.swing.JTextField txt_addPersonId;
    private javax.swing.JTextField txt_addPersonName;
    // End of variables declaration//GEN-END:variables
}
