import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**

 @author mattk and manjukl
 */
public class MainFrame extends javax.swing.JFrame
{
   DepartmentManagement dptMgt = new DepartmentManagement();
   private Department deptName;
   /**
    Creates new form MainFrame
    */
   public MainFrame()
   {
      initComponents();
      
      setTitle("Department Management");
      setSize(600, 600);
      
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_desktop = new javax.swing.JDesktopPane();
        txt_DeptName = new javax.swing.JTextField();
        lbl_DeptName = new javax.swing.JLabel();
        btn_deptNameEnter = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menu_File = new javax.swing.JMenu();
        menuItem_Exit = new javax.swing.JMenuItem();
        menu_Register = new javax.swing.JMenu();
        menu_CrsMgt = new javax.swing.JMenu();
        menuItem_AddCourse = new javax.swing.JMenuItem();
        menuItem_ListCourse = new javax.swing.JMenuItem();
        menu_PrsnMgt = new javax.swing.JMenu();
        menuItem_addPerson = new javax.swing.JMenuItem();
        menuItem_RemovePerson = new javax.swing.JMenuItem();
        menuItem_ListPerson = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_DeptName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DeptNameActionPerformed(evt);
            }
        });

        lbl_DeptName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DeptName.setText("Department Name");

        btn_deptNameEnter.setText("Enter");
        btn_deptNameEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_deptNameEnterMousePressed(evt);
            }
        });
        btn_deptNameEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deptNameEnterActionPerformed(evt);
            }
        });

        pn_desktop.setLayer(txt_DeptName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pn_desktop.setLayer(lbl_DeptName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pn_desktop.setLayer(btn_deptNameEnter, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pn_desktopLayout = new javax.swing.GroupLayout(pn_desktop);
        pn_desktop.setLayout(pn_desktopLayout);
        pn_desktopLayout.setHorizontalGroup(
            pn_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_desktopLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(pn_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_deptNameEnter)
                    .addGroup(pn_desktopLayout.createSequentialGroup()
                        .addComponent(lbl_DeptName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_DeptName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        pn_desktopLayout.setVerticalGroup(
            pn_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_desktopLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(pn_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DeptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_DeptName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deptNameEnter)
                .addGap(250, 250, 250))
        );

        menu_File.setText("File");

        menuItem_Exit.setText("Exit");
        menuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ExitActionPerformed(evt);
            }
        });
        menu_File.add(menuItem_Exit);

        menuBar.add(menu_File);

        menu_Register.setText("Register");
        menu_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_RegisterMouseClicked(evt);
            }
        });
        menuBar.add(menu_Register);

        menu_CrsMgt.setText("Manage Courses");

        menuItem_AddCourse.setText("Add Course");
        menuItem_AddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_AddCourseActionPerformed(evt);
            }
        });
        menu_CrsMgt.add(menuItem_AddCourse);

        menuItem_ListCourse.setText("List Courses");
        menuItem_ListCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ListCourseActionPerformed(evt);
            }
        });
        menu_CrsMgt.add(menuItem_ListCourse);

        menuBar.add(menu_CrsMgt);

        menu_PrsnMgt.setText("Manage People");

        menuItem_addPerson.setText("Add Person");
        menuItem_addPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_addPersonActionPerformed(evt);
            }
        });
        menu_PrsnMgt.add(menuItem_addPerson);

        menuItem_RemovePerson.setText("Remove Person");
        menuItem_RemovePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_RemovePersonActionPerformed(evt);
            }
        });
        menu_PrsnMgt.add(menuItem_RemovePerson);

        menuItem_ListPerson.setText("List People");
        menuItem_ListPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ListPersonActionPerformed(evt);
            }
        });
        menu_PrsnMgt.add(menuItem_ListPerson);

        menuBar.add(menu_PrsnMgt);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
   private void menuItem_addPersonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuItem_addPersonActionPerformed
   {//GEN-HEADEREND:event_menuItem_addPersonActionPerformed
      // TODO add your handling code here:
      addPersonFrame f = new addPersonFrame(deptName);
      pn_desktop.add(f);
      f.setVisible(true);
      
   }//GEN-LAST:event_menuItem_addPersonActionPerformed

   private void menuItem_ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuItem_ExitActionPerformed
   {//GEN-HEADEREND:event_menuItem_ExitActionPerformed
      // TODO add your handling code here:
      int confirm = JOptionPane.showConfirmDialog(null, 
            "Are you sure you want to exit this session? "
            + "\nALL DATA WILL BE LOST!",
            "Exit Session?",JOptionPane.YES_NO_OPTION);
      if (confirm == 0)
         System.exit(0);
   }//GEN-LAST:event_menuItem_ExitActionPerformed

    private void menuItem_RemovePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_RemovePersonActionPerformed
        // TODO add your handling code here:
        if (Department.count != 0)
        {
            removePersonFrame f = new removePersonFrame(deptName);
            pn_desktop.add(f);
            f.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "There are no people to delete!");
            
    }//GEN-LAST:event_menuItem_RemovePersonActionPerformed

    private void txt_DeptNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DeptNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DeptNameActionPerformed

    private void menuItem_ListPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ListPersonActionPerformed
        // TODO add your handling code here:
        if (Department.count != 0)
        {
            listPeopleFrame f = new listPeopleFrame(deptName);
            pn_desktop.add(f);
            f.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, 
                    "There are not any people in this department!");
    }//GEN-LAST:event_menuItem_ListPersonActionPerformed

    private void menuItem_AddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_AddCourseActionPerformed
        // TODO add your handling code here:
        addCourseFrame f = new addCourseFrame(deptName);
        pn_desktop.add(f);
        f.setVisible(true);        
    }//GEN-LAST:event_menuItem_AddCourseActionPerformed

    private void menuItem_ListCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ListCourseActionPerformed
        // TODO add your handling code here:
        listCourseFrame f = new listCourseFrame(deptName);
        pn_desktop.add(f);
        f.setVisible(true);   
    }//GEN-LAST:event_menuItem_ListCourseActionPerformed

    private void menu_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_RegisterMouseClicked
        // TODO add your handling code here:
        if (Department.count == 0 && Department.cCount == 0)
        {
            JOptionPane.showMessageDialog(null, "Please add people and courses first.");
        }
        else if (Department.count == 0)
            JOptionPane.showMessageDialog(null, "Please add a person first.");
        else if (Department.cCount == 0)
            JOptionPane.showMessageDialog(null, "Please add a course first.");
        else
        {
            registerCourseFrame f = new registerCourseFrame(deptName);
            pn_desktop.add(f);
            f.setVisible(true);
        }
    }//GEN-LAST:event_menu_RegisterMouseClicked

   private void btn_deptNameEnterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_deptNameEnterActionPerformed
   {//GEN-HEADEREND:event_btn_deptNameEnterActionPerformed
      // TODO add your handling code here:
      String departmentName = txt_DeptName.getText();
      Object deptObject = dptMgt.readIn(departmentName);
      deptName = (Department) deptObject;
   }//GEN-LAST:event_btn_deptNameEnterActionPerformed

   private void btn_deptNameEnterMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_deptNameEnterMousePressed
   {//GEN-HEADEREND:event_btn_deptNameEnterMousePressed
      // TODO add your handling code here:
      String departmentName = txt_DeptName.getText();
      Object deptObject = dptMgt.readIn(departmentName);
      deptName = (Department) deptObject;
      txt_DeptName.setText("Created!");
   }//GEN-LAST:event_btn_deptNameEnterMousePressed

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new MainFrame().setVisible(true);
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deptNameEnter;
    private javax.swing.JLabel lbl_DeptName;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItem_AddCourse;
    private javax.swing.JMenuItem menuItem_Exit;
    private javax.swing.JMenuItem menuItem_ListCourse;
    private javax.swing.JMenuItem menuItem_ListPerson;
    private javax.swing.JMenuItem menuItem_RemovePerson;
    private javax.swing.JMenuItem menuItem_addPerson;
    private javax.swing.JMenu menu_CrsMgt;
    private javax.swing.JMenu menu_File;
    private javax.swing.JMenu menu_PrsnMgt;
    private javax.swing.JMenu menu_Register;
    private javax.swing.JDesktopPane pn_desktop;
    private javax.swing.JTextField txt_DeptName;
    // End of variables declaration//GEN-END:variables
}
