

import java.util.InputMismatchException;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author koenenm
 */
public class removePersonFrame extends javax.swing.JInternalFrame {
    private Department dept;
   private Bag persBag = new Bag();
   private Bag corsBag = new Bag();
    /**
     * Creates new form removePersonFrame
     */
    public removePersonFrame(Department department) {
        this.dept = department;
        initComponents();
        setTitle("Remove Person");
        setSize(200, 120);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_removePersonId = new javax.swing.JTextField();
        btn_removePersonRemove = new javax.swing.JButton();
        lbl_removePersonId = new javax.swing.JLabel();

        setClosable(true);

        btn_removePersonRemove.setText("Remove");
        btn_removePersonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removePersonRemoveActionPerformed(evt);
            }
        });

        lbl_removePersonId.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_removePersonId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_removePersonRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_removePersonId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_removePersonId)
                    .addComponent(txt_removePersonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_removePersonRemove)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_removePersonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removePersonRemoveActionPerformed
        String id = txt_removePersonId.getText();
        boolean worked = false;
        try
        {
            worked = dept.isIdValidRemove(id);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        if (worked)
        {
            dept.count--;
            txt_removePersonId.setText("");
        }
    }//GEN-LAST:event_btn_removePersonRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_removePersonRemove;
    private javax.swing.JLabel lbl_removePersonId;
    private javax.swing.JTextField txt_removePersonId;
    // End of variables declaration//GEN-END:variables
}
